### ISSUE TITLE
[FEATURE] 

### ISSUE THREAD

**Issue by JavierOramas** [covid19cuba/covid19cuba-app#109]
Make default comparison with the most similar country (IE: Hungary's behavior is almost the same that Cuba has (about +/- 10 cases) of course it will have to take on account the populationof the country, given that Spain has far more population than Cuba has so, maybe will have to compare % of population instead of the raw data

**Comment by leynier** [comment]
> Make default comparison with the most similar country (IE: Hungary's behavior is almost the same that Cuba has (about +/- 10 cases) of course it will have to take on account the populationof the country, given that Spain has far more population than Cuba has so, maybe will have to compare % of population instead of the raw data

Currently, the default country is Hungary, it is static in the application, it was chosen doing an analysis similar to the one mentioned. But once inside the application, if you select another option, this will be saved, making that if you open the application again the selected option is the one that was last chosen. So this analysis would only serve to choose the option the first time it opens after installing the application.
