### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by edgaravante** [covid19cuba/covid19cuba-app#127]
Parece muy lento el.proceso de actualización diario de la información, debería haber más inmediatez en la actualización de los datos de Cuba, al mismo tiempo q los informa el MINSAP en la entrevista de las 11 AM

 **Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by sandypm007** [comment]
El proceso de actualización lo hacemos gracias al esfuerzo de un grupo de personas que toman los datos de los partes públicos del Ministerio de Salud Púlbica (MINSAP). No tenemos fuente primaria de datos directa de ninguna organización. El proceso se realiza con la mayor inmediatez posible.

**Comment by glpzzz** [comment]
> Parece muy lento el.proceso de actualización diario de la información, debería haber más inmediatez en la actualización de los datos de Cuba, al mismo tiempo q los informa el MINSAP en la entrevista de las 11 AM
 
Le invitamos a convertir a JSON el reporte de los casos antes de que acabe de la conferencia de prensa de las 11AM. No de los 40-60 casos diarios. Solo de 10, si lo logra, se gana un puesto con nosotros y tendrá la posibilidad de recibir el mismo pago que nosotros. Sabe cual es? Haga click aquí: https://github.com/covid19cuba/covid19cuba-app/issues/127

**Comment by leynier** [comment]
This issues doesn't make much sense, so it will be closed.
