### ISSUE TITLE
[FEATURE] Implement a comparison chart with regions

### ISSUE THREAD

**Issue by leynier** [covid19cuba/covid19cuba-app#137]
**Is your feature request related to a problem? Please describe.**
Implement a graph of comparison of cases, deaths, and accumulated recovery Cuba with different regions.

**Describe the solution you'd like**
Group the countries by regions and get the average of each day by region.

**Comment by norlancd** [comment]
The regions could be:
Américas (Norteamérica, Sudamérica, América Central, el Caribe)
Asia-Pacífico (Asia Central y Meridional, Noreste Asiático, Sudeste Asiático, Australia y Oceanía)
Europa (Europa del Norte, Europa del Sur, Europa del Este, Europa Occidental)
Oriente Medio/África (Oriente Medio, Norte de África, Sur de África)
