### ISSUE TITLE
[BUG] No se ve con claridad los días en el gráfico "Test (PCR) por días"

### ISSUE THREAD

**Issue by Yeikel200** [covid19cuba/covid19cuba-app#156]
Los días que se muestran bajo la gráfica no tiene separación, no se diferencia un día de otro.

![IMG_20200418_142709](https://user-images.githubusercontent.com/26438532/79656062-bc1c7500-8180-11ea-92ed-64855c30da10.jpg)

**Smartphone:**
 - Device: [Xiaomi Redmi Note 7]
 - OS: [Android 9.0]

**Comment by leynier** [comment]
Este issue expresa lo mismo que el issue #147
