### ISSUE TITLE
[FEATURE] Gráfico alternativo "Pais de importacion" a "Distribución por nacionalidad de casos en Cuba"

### ISSUE THREAD

**Issue by qPCR4vir** [covid19cuba/covid19cuba-app#18]
Al Gráfico "Distribución por nacionalidad de casos en Cuba" pudiera anadirsele un selector para que mostrara el pais desde el que aparentemente ocurrio la importacion de la infeccion. Seria bastante mas interesante que saber la nacionalidad del infectado.

**Comment by leynier** [comment]
Esa información no es muy precisa y el ministerio de salud no la maneja. Por lo que no se puede incluir.
