### ISSUE TITLE
[BUG] No se diferencia el color de la provincia de Guantánamo

### ISSUE THREAD

**Issue by Yeikel200** [covid19cuba/covid19cuba-app#75]
En el mapa por provincia no se percibe diferencia con el color de la provincia de Guantánamo, está transparente !!

![Screenshot_2020-03-31-15-37-22-473_club postdata covid19cuba](https://user-images.githubusercontent.com/26438532/78068577-a2002b80-7366-11ea-8c1f-7b06357702f2.jpg)

**Comment by leynier** [comment]
This bug was fixed
