### ISSUE TITLE
[BUG]  Extranjeros con g y otros

### ISSUE THREAD

**Issue by lukedalmau** [covid19cuba/covid19cuba-app#86]
### Otro q vi pero q no se si es un bug es q arriba sale q dice actualizacion del 1ero de abril... no se si se refiere a actualizacion de la apk o de la info... en todo caso si es de la apk... no creo q deba ser relevante estar ahi en primer plano... si es de los datos, entonces no se esta actualizando la fecha de la cual  los datos se estan actualizando(me consta q si estan actualizados los datos xq lo se pero no se si esa fecha sea la de actualización) 

![Screenshot_20200403-064156](https://user-images.githubusercontent.com/52575039/78353362-e6aee100-7577-11ea-9831-dd9da78775ae.jpg)

**Smartphone (please complete the following information):**
 - Device: Samsung Note 8
 - OS: Android 7 o por ahi
 - Browser apk de covid

**Comment by lukedalmau** [comment]
Lo edite xq ya vo q tenian arreglado lo primero q habia puesto en la red.... solo q en la apk.... sigue el extranjeros con g y los problemas de esas columnas.Hay q esperar a lanzarla

**Comment by sandypm007** [comment]
Hola, al parecer es una versión enterior de la apk. Ya estos temas están resueltos en la última versión que tenemos pública. Gracias

**Comment by lukedalmau** [comment]
Si ya vi en el de github gracias y disculpen las molestias... era q en el de cusobu y en la apk no estaba como en el de github.io 👌🏻👌🏻👌🏻
